title: Kyle Fiedler
description: I’m probably eating a taco

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jemoji
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: :compressed

exclude:
  - README
