permalink: /writing/:title
auto: true
lsi: true
paginate: 5 //the number of post per page
name: Kyle Fiedler
description: Inside the mind of a boring person
url: http://kylefiedler.com
exclude:
- README
