title: Kyle Fiedler
description: I’m probably eating a taco

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
paginate: 5
paginate_path: "/blog/:num/"

sass:
  sass_dir: _sass
  style: :compressed

exclude:
  - README
