permalink: /blog/:title
safe: true
lsi: false
pygments: true
paginate: 6 //the number of post per page
name: Kyle Fiedler
description: Inside the mind of a boring person
url: http://kylefiedler.com
exclude:
- README
