title: Kyle Fiedler
description: Kyle enjoys a well-made peanut butter and jelly sandwich, cut in two triangles

plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/blog/:num/"

sass:
  sass_dir: _sass
  style: :compressed

exclude:
  - README
